### ISSUE TITLE
Symbol missing `__gxx_personality_v0`

### ISSUE THREAD

**Issue by Zoxc** [rib/android-activity#10]
I looked up why the `agdk-egui` example didn't work for me. It seems the `__gxx_personality_v0` symbol is missing.

```
08-11 05:14:24.205  8571  8571 E AndroidRuntime: Process: co.realfit.agdkegui, PID: 8571
08-11 05:14:24.205  8571  8571 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__gxx_personality_v0" referenced by "/data/app/~~g0_VzSMaMS-455v0wTQNOQ==/co.realfit.agdkegui-Wr6x4eR22P4mMTPS3njZmw==/base.apk!/lib/arm64-v8a/libmain.so"...
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1656)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at co.realfit.agdkegui.MainActivity.<clinit>(MainActivity.java:32)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8663)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-11 05:14:24.205  8571  8571 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by rib** [comment]
hmm, that sounds vaguely related to the issue with libgcc being used for unwind handling / backtraces but libgcc was removed from the NDK toolchains. That normally leads to a clear linker error when compiling though.

What NDK toochain version are you using I wonder?

I'd maybe try upgrading to a new NDK if not on the latest, and also check you have an up to date `cargo ndk` to make sure it's compatible with NDK versions >=23 that have removed libgcc in favour of libunwind.

**Comment by Zoxc** [comment]
I moved from NDK 24.0.8215888 to 25.0.8775105 and installed the latest `cargo ndk`, but I still get the same error. I'm building on Windows.

**Comment by Zoxc** [comment]
I did try building on Linux, but that did also not help.

**Comment by rib** [comment]
yesterday I was testing with an older version 21 NDK and I just tried building agdk-egui with an r25 NDK and that compiled and ran ok for me.

(I'm also building on Windows btw)

curious. I'm not sure atm what that's going to be.

**Comment by rib** [comment]
makes me think of issues with not having the right c++ runtime library but hard to see why there should be some difference between your setup and mine.

What version of Android are you running against out of curiosity?

**Comment by Zoxc** [comment]
The emulator is Android 11 x86 and my Samsung A41 is on Android 12 AArch64.

**Comment by rib** [comment]
Just out of curiosity can you maybe try opening up `MainActivity.java` and uncommenting this line to explicitly load `c++_shared`:

```java
    static {
        // Load the STL first to workaround issues on old Android versions:
        // "if your app targets a version of Android earlier than Android 4.3
        // (Android API level 18),
        // and you use libc++_shared.so, you must load the shared library before any other
        // library that depends on it."
        // See https://developer.android.com/ndk/guides/cpp-support#shared_runtimes
        //System.loadLibrary("c++_shared");

        // Load the native library.
        // The name "android-game" depends on your CMake configuration, must be
        // consistent here and inside AndroidManifect.xml
        System.loadLibrary("main");
    }
```

**Comment by rib** [comment]
The device I'm currently testing with is Android 9 (Samsung Galaxy S8+) I haven't tried running against an emulator though

**Comment by Zoxc** [comment]
That results in `java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found`.

`libc++abi.a` and `libc++_shared.so` both contain `__gxx_personality_v0`, so I suspect I end up not linking to `libc++abi.a` for some reason.

**Comment by Zoxc** [comment]
Adding the following to the `agdk-egui` example fixed the issue:
```rust
#[link(name="c++abi", kind="static")]
extern {
    #[link_name="__gxx_personality_v0"]
    fn test();
}
```

Now there's proper Rust stuff to fix :)
```
wgpu::backend::direct: Error in Adapter::request_device: Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
08-12 00:02:04.730  5399  5426 I RustStdoutStderr: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RequestDeviceError', C:\Users\John\.cargo\git\checkouts\egui-eb35840a124b3a7a\c139e66\egui-wgpu\src\winit.rs:88:87
```

**Comment by Zoxc** [comment]
It does work on my phone, but I guess `wgpu` doesn't like the emulator.

**Comment by rib** [comment]
ah, right I forgot that you'd have to also explicitly copy libc++_shared.so out of your NDK into the libs directory before uncommenting that line.

hehe, yeah just manually defining the `__gxx_personality_v0` symbol yourself is a bit of a hack but I guess if that works for you for now, that's fine.

Right - I guess I'm not super surprised to see graphics stuff fail in an emulator, esp since wgpu will be using Vulkan by default which may unwittingly end up doing something that their GPU virtualization doesn't handle. I wonder if you'd have a bit more luck with the emulator if you try coercing wgpu to use gles instead of vulkan.

**Comment by rib** [comment]
or else maybe we can figure out some minimal wgpu Limit (I can't imagine wgpu needs to touch the compute hardware anyway) that would make it happy here - it looks like the issue isn't a failure with the GPU virtualization (what I was assuming) but it might be that the virtualized GPU is unusually limited compared to real hardware and so wgpu is then getting upset when it's querying the hardware capabilities)
